### ISSUE TITLE
NameError: uninitialized constant CompetitionRankingLeaderboard

### ISSUE THREAD

**Issue by jkauszler** [agoragames/leaderboard#68]
When trying to initialize a new leaderboard using either CompetitionRankingLeaderboard or TieRankingLeaderboard subclass I receive a `NameError: uninitialized constant` error. Default `Leaderboard.new('options')` successfully works. If I manually add the gems contents to the apps source code, everything works as expected. Ruby: 2.4.0p0 (2016-12-24 revision 57164) / Bundler version 1.16.2 / Rails: v5.2.0.

**Comment by czarneckid** [comment]
Are you requiring the right file(s)?

```ruby
2.2.1 :003 > require 'competition_ranking_leaderboard'
 => true
2.2.1 :004 > lb = CompetitionRankingLeaderboard.new('highscores')
 => #<CompetitionRankingLeaderboard:0x007fa405157f38 @leaderboard_name="highscores", @reverse=false, @page_size=25, @member_key=:member, @rank_key=:rank, @score_key=:score, @member_data_key=:member_data, @member_data_namespace="member_data", @global_member_data=false, @redis_connection=#<Redis client v3.1.0 for redis://localhost:6379/0>>
2.2.1 :005 >
```

**Comment by jkauszler** [comment]
Looks like I missed it. Glad that one was on me. Thanks for the quick response. Super useful gem. Thanks, guys.
